apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxytls
spec:
  commonName: yewhampshire.com
  dnsNames:
  - yewhampshire.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: proxytls
