apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-sentiment
  labels:
    app: comment-sentiment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: comment-sentiment
  template:
    metadata:
      labels:
        app: comment-sentiment
    spec:
      containers:
        - name: sentiment-analyzer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/var/app/comment-sentiment"]
          args:
            - "--language-keyfile"
            - "/mnt/secrets-store/languagekey"
            - "--language-endpoint"
            - "{{ .Values.languageEndpoint }}"
            - "--app-id"
            - "{{ .Values.github.appID }}"
            - "--app-keyfile"
            - "/mnt/secrets-store/happyossprivatekey"
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          volumeMounts:
            - name: secretsstore
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secretsstore
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: spc
