apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyvault.userID }}"
    keyvaultName: "{{ .Values.keyvault.name }}"
    objects:  |
      array:
        - |
          objectType: secret
          objectName: languagekey
        - |
          objectType: secret
          objectName: happyossprivatekey
        - |
          objectType: secret
          objectName: happyosswebhooksecret
    tenantId: "{{ .Values.keyvault.tenantID }}"
