apiVersion: v1
kind: Service
metadata:
  name: comment-sentiment
  labels:
    app: comment-sentiment
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: comment-sentiment
