// Code generated by "stringer -type=sentiment"; DO NOT EDIT.

package sentimentanalyzer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Positive-0]
	_ = x[Negative-1]
	_ = x[Neutral-2]
}

const _sentiment_name = "PositiveNegativeNeutral"

var _sentiment_index = [...]uint8{0, 8, 16, 23}

func (i Sentiment) String() string {
	if i < 0 || i >= Sentiment(len(_sentiment_index)-1) {
		return "sentiment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sentiment_name[_sentiment_index[i]:_sentiment_index[i+1]]
}
